### ISSUE TITLE
Escalar - logger: v2.5 taxa alta de gravação

### ISSUE THREAD

**Issue by fgnievinski** [mphwdev/mphwdev#25]
suportar altas taxas de atualização (maiores que 1 hertz -- intervalos menores que 1 segundo)

http://cta.if.ufrgs.br/issues/659

dependências:
#2 Escalar - logger: v.2.5.3 escrita imediata

**Comment by gdsantana** [comment]
Criei uma branch nova com o arquivo 20200729.ino que seria o código com a implementação da alta de atualização. Deixarei o arduino colentando os dados para ver se esta corrompendo os arquivos.

**Comment by gdsantana** [comment]
Fiz testes usando o codigo do Iuri com a biblioteca SD.h e com a SdFat.h e cheguei em alguns problemas:
1) O código usando a SD.h funciona tranquilo, sem corromper os arquivos aparentemente.

2) Mas quando troco para a SdFat.h (sem fazer nenhuma outra alteração, apenas as necessarias para usar a biblioteca) os dados do gps ficam corrompidos.

Com a SdFat.h a gente pode controlar o clock de escrita no cartão de memória, vou ver se alterando isso resolve o problema ou não.

**Comment by gdsantana** [comment]
Realizei novos testes usando versão mais nova da biblioteca mas mesmo assim o problema de corromper os arquivos continua

**Comment by gdsantana** [comment]
Fiz novos testes com taxas de atualizações de 1 Hz até 10 Hz usando a biblioteca SdFat.h e o 32u4.
Com 1Hz e 2Hz aparemente coleta o dados sem corromper os arquivos, mas com as taxas de 5 Hz e 10 Hz já mostram os arquivos corrompidos.
Segue abaixo os logs que coletei durante os teste:
https://we.tl/t-pzjJUJ1D7c

**Comment by gdsantana** [comment]
Agora, fico no aguardo de realizar novos testes com o Adafruit M0, para saber se realmente o 32u4 que não esta aguentando as altas taxas e a biblioteca SdFAT.h

**Comment by gdsantana** [comment]
Sigo no aguardo da placa M0 para fazer novos testes.

**Comment by gdsantana** [comment]
Essa semana peguei o M0 e realizei novos testes com a biblioteca SdFat.h.
Os testes que fiz foi só usando a biblioteca em si, sem nenhuma implementação da sobrescrita de arquivos. E ,aparentemente, o M0 tem poder de processamento suficiente para usar o biblioteca SdFat.h e as altas taxas de atualização.
Agora vou fazer novos testes usando o codigo que implenta a sobrescrita de arquivos para verificar se o M0 consegue rodar tranquilo.

**Comment by gdsantana** [comment]
Realizei testes com a implementação da sobrescrita e aparentemente esta tudo ok, tive um pequeno problema q logo que liga o arduino ele coleta um dado de gps errado e cria um arquivo com um novo estranho em vez de salvar no DEFAULT.log

**Comment by gdsantana** [comment]
Depois de resolver todos os problemas de:
- Achar uma nova biblioteca que tivesse as funções necessárias
- implementar a sobrescrita
- realizar testes e verificar que o 32u4 não é potente suficiente para sobrescrita e as altas taxas de atualizações
- realizar testes no M0 que por sua vez foi potente suficiente para essas 2 operações
Assim, acredito que finalizo a implementação da sobrescrita de arquivos. Irei subir o codigo mais atualizado para a branch da sobrescrita.
